### ISSUE TITLE
value error

### ISSUE THREAD

**Issue by mythrireddy** [kesaroid/Glaucoma-Detection#1]
i am getting value error while running this code 
![1](https://user-images.githubusercontent.com/45193162/56459753-f0b2f080-63b5-11e9-9eb2-3bb52fce34a5.png)

can any one give a solution for this problem and which version of anaconda software should be used....is this problem related to software or code...i installed anaconda 3.7 version

**Comment by kesaroid** [comment]
Hello, It seems that CV2 has changed its documentation slightly. Due to the [following commit](https://github.com/kesaroid/Glaucoma-Detection/commit/db526ce356512d9c20d437fa52930ff97b623109#diff-8a2278b7033521f0b8a235bb4818c319) It is now working fine.

I believe the issue is closed.
