### ISSUE TITLE
ERROR-model = load_model('C:/ProgramData/Anaconda3/Lib/site-packages/tables/tests/f1.h5')

### ISSUE THREAD

**Issue by kschandra31** [kesaroid/Glaucoma-Detection#5]
Hi,This is K.Santosh , B.Tech CSE final year student. I am getting the following error.Trying to rectify it but unable to do it.

ERROR-model = load_model('C:/ProgramData/Anaconda3/Lib/site-packages/tables/tests/f1.h5')

Help me out on this @ How to resolve it.

![image](https://user-images.githubusercontent.com/60032752/72662427-fef97000-3a0c-11ea-8a16-bb60882be4ce.png)

**Comment by kesaroid** [comment]
Since it is an OSError, I think it is an error in the path of your pre-trained weights.
